# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 906c070458efec63199f089c046e8b3ca4e6eb114bd7b5104ebfd971267fb191d97cf435788c818c1154df79fe8529f94b672465afee43dd283f697e03ebd4a4

test:
  secret_key_base: 336f7325a375f5e832db73f9b0d919a145285b519c40df2f8c2c2900884a6260a9b0d10895d2ef3fad0174ebefa2ccb52f8c021f5164385237a673e4756f491a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
